github_checks:
  annotations: false
parsers:
  go:
    partials_as_hits: true
ignore:
  - "cmd/**"
  - "apispec/**"
  - "**/*_string.go"
  - "**/*_err.go"
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 3%
    patch:
      default:
        target: 50%
component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 3%
      - type: patch
        target: 50%
  individual_components:
    - component_id: gbkr
      name: gbkr
      paths:
        - "*.go"
    - component_id: models
      name: models
      paths:
        - "models/**"
