version: "2"

linters:
  default: none
  enable:
    - containedctx
    - contextcheck
    - errcheck
    - errname
    - errorlint
    - gocritic
    - gosec
    - govet
    - ineffassign
    - modernize
    - nolintlint
    - revive
    - staticcheck
    - thelper
    - unused
    - usestdlibvars
  settings:
    gosec:
      excludes:
        - G104 # duplicates errcheck
  exclusions:
    generated: strict
    presets:
      - comments
      - std-error-handling
    rules:
      - path: '(.+)_test\.go'
        linters:
          - revive
