name: CI
permissions:
  contents: read

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run ci
      - run: cd flex && mise run ci
      - uses: codecov/codecov-action@v5
        with:
          files: coverage.out
          flags: gbkr
          name: gbkr
      - uses: codecov/codecov-action@v5
        with:
          files: flex/coverage.out
          flags: flex
          name: flex
